### PR TITLE
Bump to standard-cnpg:15.3.0-1-0c19c7e

### PR DESCRIPTION
**Pull request by ianstanton**
Bump image to `standard-cnpg:15.3.0-1-0c19c7e` in the following stacks:
- `Standard`
- `MessageQueue`
- `OLAP`
- `OLTP`

### CODE REVIEW

**Review by nhudson — CHANGES_REQUESTED** [review]
You might want to also update the default images as well

https://github.com/tembo-io/tembo-stacks/blob/a1fb6ab7d023a1ed5db0b8707606d30498a31de8/tembo-operator/src/defaults.rs#L40

https://github.com/tembo-io/tembo-stacks/blob/a1fb6ab7d023a1ed5db0b8707606d30498a31de8/tembo-operator/src/defaults.rs#L45

**Comment by nhudson** [comment]
> > You might want to also update the default images as well
> > https://github.com/tembo-io/tembo-stacks/blob/a1fb6ab7d023a1ed5db0b8707606d30498a31de8/tembo-operator/src/defaults.rs#L41
> > 
> > https://github.com/tembo-io/tembo-stacks/blob/a1fb6ab7d023a1ed5db0b8707606d30498a31de8/tembo-operator/src/defaults.rs#L45
> 
> Thanks!

You will need to run `just generate-crd` afterwards and add the updated `crd.yaml` too.

**Review by nhudson — APPROVED** [review]

**Comment by ianstanton** [comment]
Bumping `ml-cnpg` before merging this one https://github.com/tembo-io/tembo-images/pull/27

**Comment by ianstanton** [comment]
@nhudson @ChuckHend I also updated the `ml-cnpg` image

**Review by nhudson — APPROVED** [review]
LGTM!  FYI You will also need to update the cp-webserver stacks as well with another PR
https://github.com/tembo-io/control-plane/tree/main/cp-webserver/src/stacks

**Pull request merged**
